.\" Manpage for lisp C API
.\" Contact howe.r.j.89@gmail.com to correct errors or typos.
.TH man 1 "18 Sep 2014" "0.1.X" "lisp man page"
.SH NAME
lisp \- C API for a small text processing oriented embeddable lisp interpreter.
.SH SYNOPSIS
#include <lisp.h>

.SH DESCRIPTION
lisp is a small lisp interpreter written in mostly ANSI C for scripting,
glue logic, prototyping and general hacking around.

The API, while not stable at the moment, has the goals to be incredibly
simple to set up and use. I will not document anything here at the moment,
due to the lack of any standard.

It should be safe to call C functions from C++, everything is wrapped up
with extern "C" {}; in the headers so you do not have to worry about it.
.SH SEE ALSO
lisp(1)
.SH BUGS
Seeing as this is a pre-version-1.0 not only are there many bugs but the
language is not even that stable. Also the name itself is a bug, it is not
exactly unique!

If the project gets too big (>10kLOC) then this is also to be considered a
bug.

Much like the language, the API itself is also not stable, so do not expect
anything from it.
.SH AUTHOR
Richard James Howe (howe.r.j.89@gmail.com)
