.\" Manpage for lisp.
.\" Contact howe.r.j.89@gmail.com to correct errors or typos.
.TH man 1 "18 Sep 2014" "0.1.X" "lisp man page"
.SH NAME
lisp \- small lisp interpreter
.SH SYNOPSIS
.B lisp 
[OPTION] ... [FILE] ... [EXPRESSION] ...
.SH DESCRIPTION
.\" I should reference other lisp interpreters using interpreter(1) syntax
.\" And also the man page for this lisp interpreters C API
lisp is a small lisp interpreter written in mostly ANSI C for scripting,
glue logic, prototyping and general hacking around.
.SH OPTIONS

.TP
.B -h
Show a help message.

.SH SEE ALSO
lisp(3)
.SH BUGS
Seeing as this is a pre-version-1.0 not only are there many bugs but the
language is not even that stable.
.SH AUTHOR
Richard James Howe (howe.r.j.89@gmail.com)
