.\" Manpage for lisp.
.\" Contact howe.r.j.89@gmail.com to correct errors or typos.
.TH man 1 "18 Sep 2014" "0.2.X" "lisp man page"
.SH NAME
lisp \- small text processing oriented lisp interpreter
.SH SYNOPSIS
lisp [OPTION] ... [FILE] ... [EXPRESSION] ...
.SH DESCRIPTION
.\" I should reference other lisp interpreters using interpreter(1) syntax
.\" And also the man page for this lisp interpreters C API
lisp is a small lisp interpreter written in mostly ANSI C for scripting,
glue logic, prototyping and general hacking around.
.SH OPTIONS

.TP
.B -h
Show a help message.
.TP
.B  -d   
Extra debugging information; memory allocations, printing globals, file IO, ...
.TP
.B  -c   
Color on.
.TP
.B  -p   
Print out full procedure.
.TP
.B  -e   
Next argument is an expression to lisp_evaluate.
.TP
.B  -o   
Next argument is a file to write to.
.TP
.B  -V   
Version number.

.SH SEE ALSO
lisp(3)
.SH BUGS
Seeing as this is a pre-version-1.0 not only are there many bugs but the
language is not even that stable. Also the name itself is a bug, it is not
exactly unique!

If the project gets too big (>10kLOC) then this is also to be considered a
bug. This excludes any test units/test benches, these should be as long
as possible.
.SH AUTHOR
Richard James Howe (howe.r.j.89@gmail.com)
